spring:

  datasource:
    url: jdbc:mysql://localhost:3306/school-app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: manchester81

  jpa:

    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
